[package]
name = "pysmesh"
version = "0.1.0"
edition = "2024"

[lib]
name = "pysmesh"
crate-type = ["cdylib"]

[dependencies]
log = "0.4.27"
smesh = { path="../" }
numpy = "0.24.0"
pyo3 = { version = "0.24.1", features = ["extension-module", "multiple-pymethods"] }
pyo3-log = "0.12"