name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lib:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Fmt
      run: cargo fmt --check --all
    - name: Clippy
      run: cargo clippy
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  examples:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: sudo apt-get install -y gmsh
    - name: Run examples/dual_mesh_2d
      run: cd examples/dual_mesh_2d; cargo run

  python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Python bindings
      run: cd pytmesh; pip install vtk==9.3; pip install -e .; python -m unittest discover
